services:
  db:
      image: postgres:13
      environment:
        POSTGRES_USER: testuser
        POSTGRES_PASSWORD: testpass
        POSTGRES_DB: testdb
      volumes:
        - postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
        interval: 5s
        timeout: 5s
        retries: 5

volumes:
  postgres_data: